const LOCAL_LOGOS = new Set([
  'proton/aipc_tokencreate','proton/airk_tokencreate','proton/amari_amarifdn','proton/atom_tokencreate','proton/bank_tokencreate','proton/blpad_tokencreate','proton/bonds_tokencreate','proton/boss_tokencreate','proton/cat_tokencreate','proton/circus_pbcbank','proton/clan_clanx','proton/coreum_applex','proton/ctravl_tokencreate','proton/cyphr_tokencreate','proton/dank_electronteam','proton/dkt_tokencreate','proton/dog_tokencreate','proton/dpus_simpletoken','proton/easy_mon3y','proton/frink_xrpl2','proton/gbx_tokencreate','proton/grams_goldmon3y','proton/gumdrop_tokencreate','proton/index_xfund','proton/isi_tokencreate','proton/ksto_tokencreate','proton/loan_loantoken','proton/lofi_loficlub','proton/meme_m3m3','proton/metal_xtokens','proton/mormin_tokencreate','proton/nlmt_tokencreate','proton/nutmeg_tokencreate','proton/owl_tokencreate','proton/phxp_tokencreate','proton/pika_tokencreate','proton/pnut_tokencreate','proton/ppx_tokencreate','proton/prkl_tokencreate','proton/purpl_tokencreate','proton/purr_purrspace','proton/pussy_xprpussydao','proton/shroom_tokencreate','proton/silver_silverbank','proton/snips_snipcoins','proton/strx_storex','proton/tdbn_tokencreate','proton/ubqt_ubitquityllc','proton/won_w3won','proton/wtt_worthless','proton/xausurf_tokencreate','proton/xbsv_teranode','proton/xbtc_xtokens','proton/xdc_xtokens','proton/xdoge_xtokens','proton/xeth_xtokens','proton/xhbar_xtokens','proton/xltc_xtokens','proton/xmd_xmdtoken','proton/xmt_xtokens','proton/xpax_xtokens','proton/xpaxg_xtokens','proton/xpyusd_xtokens','proton/xrplt_xprn','proton/xrplt_xxrpl2','proton/xrpx_tokencreate','proton/xusdc_xtokens','proton/xusdt_xtokens','proton/xxlm_xtokens','proton/yacht_tokencreate',
  'wax/aether_erplanet','wax/aether_token.aether','wax/aether_tokenaether','wax/agar_tokenagar','wax/aigod_aigodtokenwx','wax/aimr_aimrmeromai','wax/aosx_ageofswordsx','wax/aubar_trovenblade1','wax/beggars_beggarstogm','wax/butterz_buzzingarden','wax/buzz_buzzingarden','wax/caterz_buzzingarden','wax/chad_chadtoken.gm','wax/chad_chadtokengm','wax/cheese_cheeseburger','wax/chsr_chausartoken','wax/cmx_tokenmf','wax/cthulhu_meta33matrix','wax/deal_dealwithitwx','wax/dmt_defiminingtf','wax/dragonz_buzzingarden','wax/dusk_duskonmars','wax/fgl_fgltokenmgmt','wax/forge_kscopesgm','wax/hel_moonmhe3tokn','wax/honey_nfthivehoney','wax/hopperz_buzzingarden','wax/kek_waxpepetoken','wax/king_alphawaxfun','wax/krypton_kryptoncoins','wax/ladyz_buzzingarden','wax/leef_leefmaincorp','wax/loot_warsaken','wax/lsw_lsw.alcor','wax/lsw_lswalcor','wax/lswax_tokenfusion','wax/lux_xcryptochips','wax/martia_martia','wax/mnk_monkeybored1','wax/mortals_vicventura21','wax/nbmact_battleminers','wax/nbmcon_battleminers','wax/nbmfus_battleminers','wax/nbmmin_battleminers','wax/nima_odysseygm','wax/nwo_cointreasure','wax/olt_outlawtokenp','wax/parausd_parareserves','wax/pgl_prospectorsw','wax/purr_tokenyeet','wax/pxj_pixeljourney','wax/rook_pixilminirpg','wax/rum_captainshelm','wax/rust_tokenrust','wax/shell_tokengr','wax/shit_meta33matrix','wax/soren_farfromhomes','wax/sqj_sugarqueenj2','wax/tide_twitchy1gm','wax/tlm_alien.worlds','wax/tlm_alienworlds','wax/tomatoe_maestrobeatz','wax/trash_cleanuptoken','wax/triple_tokentriple','wax/usdt_usdt.alcor','wax/usdt_usdtalcor','wax/wax_eosio.token','wax/waxdao_tokenwaxdao','wax/waxusdc_eth.token','wax/waxusdc_ethtoken','wax/waxusdt_ethtoken','wax/waxwbtc_ethtoken','wax/waxweth_ethtoken','wax/wombat_wombattokens','wax/wpixal_pixeljourney','wax/wuf_wuffi','wax/xps_xpsgametoken','wax/yeet_tokenyeet',
])

const OPTIMIZED_LOGOS = new Set([
  'proton/boss_tokencreate', 'proton/dkt_tokencreate', 'proton/dpus_simpletoken',
  'proton/isi_tokencreate', 'proton/lofi_loficlub', 'proton/prkl_tokencreate',
  'proton/shroom_tokencreate', 'proton/tdbn_tokencreate', 'proton/xausurf_tokencreate',
  'wax/parausd_parareserves',
])

export function getLocalLogoUrl(chainId: string, tokenId: string): string | null {
  const dash = tokenId.indexOf('-')
  if (dash <= 0) return null
  const key = `${chainId}/${tokenId.slice(0, dash).trim().toLowerCase()}_${tokenId.slice(dash + 1).trim().toLowerCase()}`
  return LOCAL_LOGOS.has(key) ? `/token-logos/${key}.${OPTIMIZED_LOGOS.has(key) ? 'avif' : 'png'}` : null
}
